#!/usr/bin/env python3
"""Generate fd_fixtures_wbtest.mbt from the bulletin samples in tests/fixtures/.

The samples are real products captured from the Aviation Weather Center
text data API:

    curl -s "https://aviationweather.gov/api/data/windtemp?region=us&fcst=06" \
        -o tests/fixtures/fd1us1_sample.txt
    curl -s "https://aviationweather.gov/api/data/windtemp?region=us&fcst=12" \
        -o tests/fixtures/fd2us1_sample.txt
    curl -s "https://aviationweather.gov/api/data/windtemp?region=all&fcst=06&level=high" \
        -o tests/fixtures/fd_high_sample.txt

Each sample becomes a MoonBit string constant holding the product exactly as
received, so the tests parse and re-format the real thing.

Usage:
    python scripts/gen_fixtures.py > fd_fixtures_wbtest.mbt
"""

import pathlib
import sys

FIXTURES = [
    ("fd1us1_sample.txt", "fixture_fd1us1", "the low-level 6-hour product (FD1US1)"),
    ("fd2us1_sample.txt", "fixture_fd2us1", "the low-level 12-hour product (FD2US1)"),
    ("fd_high_sample.txt", "fixture_fd8us7", "the high-level product (FD8US7)"),
]

HEADER = """///|
/// Winds and temperatures aloft bulletins used by the tests.
///
/// These are real products captured from the Aviation Weather Center text
/// data API. Generated by `scripts/gen_fixtures.py`; do not edit by hand.
"""


def moon_string(text: str) -> str:
    """A MoonBit array of lines for `text`, joined at run time."""
    lines = text.split("\n")
    if lines and lines[-1] == "":
        lines = lines[:-1]
    body = []
    for line in lines:
        escaped = line.replace("\\", "\\\\").replace('"', '\\"')
        body.append(f'  "{escaped}",')
    return "[\n" + "\n".join(body) + "\n].join(\"\\n\") + \"\\n\""


def main() -> None:
    root = pathlib.Path(__file__).resolve().parent.parent
    out = [HEADER]
    for filename, ident, note in FIXTURES:
        path = root / "tests" / "fixtures" / filename
        text = path.read_text(encoding="utf-8")
        out.append(f"///|\n/// {note}, {len(text)} bytes.\n")
        out.append(f"let {ident} : String = {moon_string(text)}\n")
    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    main()
