#!/usr/bin/env python3
"""Generate MoonBit sources from the bulletin samples in tests/fixtures/.

The samples are real products captured from the Aviation Weather Center
text data API:

    curl -s "https://aviationweather.gov/api/data/windtemp?region=us&fcst=06" \
        -o tests/fixtures/fd1us1_sample.txt
    curl -s "https://aviationweather.gov/api/data/windtemp?region=us&fcst=12" \
        -o tests/fixtures/fd2us1_sample.txt
    curl -s "https://aviationweather.gov/api/data/windtemp?region=all&fcst=06&level=high" \
        -o tests/fixtures/fd_high_sample.txt

Each sample becomes a MoonBit string constant holding the product exactly as
received, so the tests parse and re-format the real thing, the command line
demo plans against the real thing, and the benchmarks run on the real thing.

Usage:
    python scripts/gen_fixtures.py > fd_fixtures_wbtest.mbt
    python scripts/gen_fixtures.py --cli > cmd/main/sample.mbt
    python scripts/gen_fixtures.py --bench > benchmarks/sample.mbt
"""

import collections
import pathlib
import sys

Fixture = collections.namedtuple("Fixture", "filename test cli bench note")

FIXTURES = [
    Fixture(
        "fd1us1_sample.txt",
        "fixture_fd1us1",
        "sample_fd1us1",
        "bench_fd1us1",
        "the low-level 6-hour product (FD1US1)",
    ),
    Fixture(
        "fd2us1_sample.txt",
        "fixture_fd2us1",
        "sample_fd2us1",
        "bench_fd2us1",
        "the low-level 12-hour product (FD2US1)",
    ),
    Fixture(
        "fd_high_sample.txt",
        "fixture_fd8us7",
        "sample_fd8us7",
        "bench_fd8us7",
        "the high-level product (FD8US7)",
    ),
]

TEST_HEADER = """///|
/// Winds and temperatures aloft bulletins used by the tests.
///
/// These are real products captured from the Aviation Weather Center text
/// data API. Generated by `scripts/gen_fixtures.py`; do not edit by hand.
"""

CLI_HEADER = """///|
/// The winds and temperatures aloft products the command line demo plans
/// against, by the name given with `--product`.
///
/// These are real products captured from the Aviation Weather Center text
/// data API. Generated by `scripts/gen_fixtures.py --cli`; do not edit by
/// hand.
"""

BENCH_HEADER = """///|
/// The winds and temperatures aloft product the benchmarks run against.
///
/// A real product captured from the Aviation Weather Center text data API,
/// the same one the tests use. Generated by `scripts/gen_fixtures.py
/// --bench`; do not edit by hand.
"""


def moon_string(text: str) -> str:
    """A MoonBit array of lines for `text`, joined at run time."""
    lines = text.split("\n")
    if lines and lines[-1] == "":
        lines = lines[:-1]
    body = []
    for line in lines:
        escaped = line.replace("\\", "\\\\").replace('"', '\\"')
        body.append(f'  "{escaped}",')
    return "[\n" + "\n".join(body) + "\n].join(\"\\n\") + \"\\n\""


def main() -> None:
    arguments = sys.argv[1:]
    if "--bench" in arguments:
        # One product is enough for the benchmarks: parsing a second one only
        # makes the run longer.
        header, ident_of, fixtures = BENCH_HEADER, lambda f: f.bench, FIXTURES[:1]
    elif "--cli" in arguments:
        header, ident_of, fixtures = CLI_HEADER, lambda f: f.cli, FIXTURES
    else:
        header, ident_of, fixtures = TEST_HEADER, lambda f: f.test, FIXTURES
    root = pathlib.Path(__file__).resolve().parent.parent
    out = [header]
    for fixture in fixtures:
        path = root / "tests" / "fixtures" / fixture.filename
        text = path.read_text(encoding="utf-8")
        out.append(f"///|\n/// {fixture.note}, {len(text)} bytes.\n")
        out.append(f"let {ident_of(fixture)} : String = {moon_string(text)}\n")
    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    main()
